# fix_bab1.py - Replace BAB I with complete academic structure
import os

filepath = r'e:\Nusa Putra\S2\Semester 2\Business Intellegence\Penelitian\Analisis Bit Coin\05_Reports\Proposal_Tesis_Bitcoin_BI_Indo.html'

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

bab1_start = content.find('<h1>BAB I: PENDAHULUAN</h1>')
bab2_start = content.find('<h1>BAB II: KAJIAN TEORITIS DAN TINJAUAN PUSTAKA</h1>')

print(f'BAB I at index: {bab1_start}')
print(f'BAB II at index: {bab2_start}')

new_bab1 = (
    "<h1>BAB I: PENDAHULUAN</h1>\n\n"

    "    <h2>1.1 Latar Belakang</h2>\n"
    "    <p>Perkembangan teknologi digital selama satu dekade terakhir telah secara masif mengubah lanskap sistem keuangan\n"
    "        global. Kemunculan aset kripto&mdash;terutama Bitcoin (BTC)&mdash;sebagai kelas aset baru yang bernilai triliunan\n"
    "        dolar telah mendisrupsi paradigma investasi tradisional secara fundamental. Berdasarkan data CoinMarketCap per\n"
    "        tahun 2024, kapitalisasi pasar Bitcoin telah melampaui angka 1,2 triliun dolar Amerika Serikat, menjadikannya\n"
    "        aset digital dengan valuasi terbesar di dunia [1].</p>\n"
    "    <p>Namun di balik potensi keuntungan yang sangat besar tersebut, pasar cryptocurrency&mdash;terutama\n"
    "        Bitcoin&mdash;memiliki karakteristik yang sangat berbeda dari pasar konvensional. Pasar ini beroperasi penuh\n"
    "        selama 24 jam sehari dan 7 hari seminggu tanpa jeda, bersifat sangat terdesentralisasi, tidak terikat regulasi\n"
    "        tunggal, dan sangat rentan terhadap perubahan sentimen makroekonomi dan faktor eksternal seperti kebijakan\n"
    "        pemerintah, perkembangan teknologi blockchain, serta pengaruh tokoh-tokoh berpengaruh di media sosial. Kondisi\n"
    "        inilah yang menyebabkan pergerakan harga Bitcoin bersifat <em>non-linear</em>, penuh <em>noise</em>, dan\n"
    "        sangat sulit diprediksi [2], [3].</p>\n"
    "    <p>Metode analisis finansial tradisional&mdash;seperti model <em>Autoregressive Integrated Moving Average</em>\n"
    "        (ARIMA) dan <em>Generalized Autoregressive Conditional Heteroskedasticity</em> (GARCH)&mdash;telah terbukti\n"
    "        tidak mampu mengakomodasi kompleksitas data pasar kripto. Model-model tersebut mensyaratkan kondisi data yang\n"
    "        <em>stasioner</em> dan mengasumsikan hubungan linier antar variabel, kondisi yang hampir tidak pernah\n"
    "        terpenuhi dalam data Bitcoin berfrekuensi tinggi [4], [5]. Kegagalan ini mendorong komunitas riset untuk\n"
    "        beralih ke paradigma komputasi yang lebih canggih, yakni arsitektur <em>Deep Learning</em> berbasis Jaringan\n"
    "        Saraf Tiruan (JST) yang mampu memodelkan dependensi temporal non-linear secara otomatis [6].</p>\n"
    "    <p>Di antara berbagai arsitektur <em>Deep Learning</em>, model berbasis <em>Recurrent Neural Network</em> (RNN)\n"
    "        dengan mekanisme gerbang memori telah terbukti dominan dalam pemodelan deret waktu finansial. Arsitektur\n"
    "        <em>Long Short-Term Memory</em> (LSTM) yang diperkenalkan oleh Hochreiter dan Schmidhuber [9] mampu mengatasi\n"
    "        masalah <em>vanishing gradient</em> pada RNN standar melalui mekanisme gerbang selektif (input, forget,\n"
    "        output). Selanjutnya, arsitektur <em>Gated Recurrent Unit</em> (GRU) yang dikembangkan oleh Cho dkk. [10]\n"
    "        hadir sebagai penyederhanaan LSTM yang lebih efisien secara komputasi namun tetap kompetitif dalam hal\n"
    "        akurasi prediksi.</p>\n"
    "    <p>Meskipun demikian, terdapat kesenjangan kritis yang belum banyak dieksplorasi dalam literatur: mayoritas\n"
    "        penelitian yang ada hanya menghasilkan angka prediksi harga secara terisolasi, tanpa mengintegrasikan keluaran\n"
    "        model tersebut ke dalam sebuah sistem <em>Business Intelligence</em> (BI) yang siap digunakan oleh para\n"
    "        pengambil keputusan di dunia nyata. Seorang manajer investasi tidak dapat mengambil keputusan strategis\n"
    "        semata dari nilai RMSE sebuah model; mereka membutuhkan metrik bisnis yang terukur dan dapat ditafsirkan,\n"
    "        seperti <em>Win Rate</em> (akurasi arah pergerakan pasar), <em>Sharpe Ratio</em> (efisiensi imbal hasil per\n"
    "        unit risiko), dan <em>Value at Risk</em> (estimasi kerugian maksimum pada tingkat kepercayaan tertentu)\n"
    "        [13], [14].</p>\n"
    "    <p>Untuk menjawab kesenjangan tersebut, penelitian ini merancang sebuah <em>kerangka kerja Business Intelligence\n"
    "        empat lapis</em> (4-Layer BI Framework) yang mengintegrasikan seluruh pipeline&mdash;mulai dari akuisisi data\n"
    "        Big Data melalui Binance API, rekayasa fitur teknikal (15 indikator), pelatihan model komparatif (LSTM, GRU,\n"
    "        XGBoost), hingga penyajian hasil dalam antarmuka <em>Decision Support Dashboard</em> yang dapat dioperasikan\n"
    "        secara langsung oleh praktisi industri. Penelitian ini menggunakan dataset berfrekuensi sangat tinggi sebanyak\n"
    "        43.788 rekaman data historis Bitcoin per jam dalam rentang lima tahun (2021&ndash;2026), yang secara inheren\n"
    "        memenuhi karakteristik fondamental Big Data (Volume, Velocity, Variety, Veracity, Value) [1], [19].</p>\n\n"

    "    <h2>1.2 Identifikasi Masalah</h2>\n"
    "    <p>Berdasarkan uraian latar belakang di atas, dapat diidentifikasi sejumlah permasalahan mendasar yang menjadi\n"
    "        motivasi utama penelitian ini:</p>\n"
    '    <ol class="rumusan">\n'
    "        <li>Model prediksi tradisional berbasis statistik (ARIMA, GARCH) terbukti tidak efektif untuk data pasar\n"
    "            cryptocurrency yang bersifat non-linear, non-stasioner, dan memiliki frekuensi tinggi, sehingga\n"
    "            menghasilkan tingkat kesalahan prediksi yang sangat tinggi [4], [5].</li>\n"
    "        <li>Terdapat kurangnya penelitian komparatif yang secara sistematis dan berimbang membandingkan performa\n"
    "            arsitektur LSTM, GRU, dan XGBoost menggunakan metodologi anti-kebocoran data (<em>Walk-Forward\n"
    "            Validation</em>) pada dataset Bitcoin berskala besar (43.788 rekaman per jam).</li>\n"
    "        <li>Sebagian besar riset yang ada hanya menghasilkan metrik performa teknis (RMSE, MAE, MAPE) secara\n"
    "            terisolasi, tanpa mentransformasikan keluaran tersebut ke dalam indikator keputusan bisnis yang relevan\n"
    "            seperti <em>Win Rate</em>, <em>Sharpe Ratio</em>, dan <em>Value at Risk</em> (VaR).</li>\n"
    "        <li>Belum terdapat kerangka kerja <em>Business Intelligence</em> yang komprehensif dan terintegrasi\n"
    "            (<em>end-to-end</em>) yang menghubungkan pipeline Big Data, model Deep Learning, dan sistem pendukung\n"
    "            keputusan eksekutif dalam satu ekosistem operasional yang utuh dan reprodusibel.</li>\n"
    "        <li>Interpretabilitas model <em>Deep Learning</em> dalam konteks prediksi finansial masih menjadi\n"
    "            tantangan, sehingga diperlukan metode seperti SHAP (<em>SHapley Additive exPlanations</em>) untuk\n"
    "            memvalidasi dan menjelaskan kontribusi setiap fitur secara transparan (<em>Explainable AI</em>)\n"
    "            [20], [21].</li>\n"
    "    </ol>\n\n"

    "    <h2>1.3 Rumusan Masalah</h2>\n"
    "    <p>Merujuk pada identifikasi masalah yang telah diuraikan, penelitian ini merumuskan pertanyaan penelitian\n"
    "        sebagai berikut:</p>\n"
    '    <ol class="rumusan">\n'
    "        <li>Bagaimana merancang dan mengimplementasikan kerangka kerja <em>Business Intelligence</em> empat lapis\n"
    "            yang mampu mengintegrasikan pipeline Big Data dari sumber API Binance hingga antarmuka <em>Decision\n"
    "            Support Dashboard</em> secara komprehensif dan deterministik?</li>\n"
    "        <li>Algoritma mana&mdash;<em>Long Short-Term Memory</em> (LSTM), <em>Gated Recurrent Unit</em> (GRU), atau\n"
    "            XGBoost sebagai baseline&mdash;yang menghasilkan performa prediksi harga Bitcoin terbaik berdasarkan\n"
    "            metrik kesalahan kuantitatif (RMSE, MAE, MAPE) ketika dievaluasi menggunakan metodologi\n"
    "            <em>Walk-Forward Validation</em> yang bebas dari kebocoran data?</li>\n"
    "        <li>Bagaimana karakteristik dan implikasi dari <em>tradeoff</em> performa yang terjadi antara model GRU\n"
    "            (yang unggul dalam presisi numerik dengan RMSE 0,1058) dan model LSTM (yang unggul dalam akurasi arah\n"
    "            pergerakan pasar dengan <em>Win Rate</em> 72,3%) untuk konteks pengambilan keputusan investasi yang\n"
    "            berbeda?</li>\n"
    "        <li>Fitur teknikal mana dari 15 indikator yang direkayasa yang memiliki kontribusi prediktif paling\n"
    "            signifikan terhadap performa model, dan bagaimana hal tersebut dapat divalidasi secara transparan\n"
    "            menggunakan nilai SHAP (<em>SHapley Additive exPlanations</em>)?</li>\n"
    "        <li>Bagaimana keluaran prediksi model <em>Deep Learning</em> dapat ditransformasikan secara algoritmik ke\n"
    "            dalam metrik risiko finansial eksekutif (<em>Sharpe Ratio</em>, <em>Value at Risk</em>) dan disajikan\n"
    "            dalam <em>BI Dashboard</em> yang <em>actionable</em> bagi para manajer investasi?</li>\n"
    "    </ol>\n\n"

    "    <h2>1.4 Tujuan Penelitian</h2>\n"
    "    <p>Sejalan dengan rumusan masalah yang telah ditetapkan, penelitian ini bertujuan untuk:</p>\n"
    '    <ol class="rumusan">\n'
    "        <li>Merancang, membangun, dan memvalidasi kerangka kerja <em>Business Intelligence</em> empat lapis\n"
    "            (4-Layer BI Framework) yang mengintegrasikan seluruh tahapan dari akuisisi Big Data, proses ETL,\n"
    "            komputasi prediktif, hingga presentasi analitik BI dalam satu ekosistem yang reprodusibel\n"
    "            (<em>deterministically reproducible</em>).</li>\n"
    "        <li>Melakukan perbandingan performa prediksi harga Bitcoin secara komprehensif dan berimbang antara\n"
    "            arsitektur LSTM, GRU, dan XGBoost menggunakan dataset 43.788 rekaman per jam (2021&ndash;2026)\n"
    "            dengan metodologi <em>Walk-Forward Validation</em>.</li>\n"
    "        <li>Mengidentifikasi, mengkuantifikasi, dan menginterpretasikan <em>tradeoff</em> fundamental yang terjadi\n"
    "            antara presisi numerik dan akurasi arah pergerakan pasar (<em>directional accuracy</em>) guna\n"
    "            memberikan rekomendasi model yang tepat sesuai konteks penggunaan di dunia investasi nyata.</li>\n"
    "        <li>Mengevaluasi dan memvalidasi tingkat kepentingan relatif setiap fitur teknikal dari 15 indikator yang\n"
    "            direkayasa menggunakan metode SHAP untuk memastikan transparansi, interpretabilitas, dan kualitas\n"
    "            ilmiah dari model yang dibangun (<em>Explainable AI</em>).</li>\n"
    "        <li>Mentransformasikan keluaran prediktif model Deep Learning ke dalam metrik risiko finansial\n"
    "            eksekutif&mdash;termasuk <em>Sharpe Ratio</em> (LSTM: 1,45), <em>Value at Risk</em> (VaR 95%: -2,34%),\n"
    "            dan <em>Directional Win Rate</em> (LSTM: 72,3%)&mdash;yang disajikan dalam prototipe <em>BI Decision\n"
    "            Support Dashboard</em> yang fungsional dan siap dioperasikan oleh manajemen lembaga keuangan.</li>\n"
    "    </ol>\n\n"

    "    <h2>1.5 Manfaat Penelitian</h2>\n"
    "    <p>Penelitian ini diharapkan memberikan kontribusi yang bermakna pada dua ranah utama:</p>\n"
    "    <p><strong>a. Manfaat Teoritis (Akademis)</strong></p>\n"
    '    <ul class="manfaat">\n'
    "        <li>Memberikan kontribusi ilmiah berupa kerangka kerja <em>BI-ML Framework</em> yang terintegrasi dan\n"
    "            dapat dijadikan referensi metodologis bagi penelitian lanjutan di bidang Informatika Finansial\n"
    "            (<em>Financial Informatics</em>) dan Analitika Big Data.</li>\n"
    "        <li>Mengisi celah (<em>research gap</em>) dalam literatur dengan menyajikan studi komparatif mendalam\n"
    "            antara LSTM, GRU, dan XGBoost menggunakan dataset Bitcoin berskala penuh dengan metodologi validasi\n"
    "            yang ketat (<em>Walk-Forward Validation</em>).</li>\n"
    "        <li>Membuktikan secara empiris keberadaan <em>tradeoff</em> antara akurasi numerik (RMSE: GRU 0,1058\n"
    "            vs. LSTM 0,1145) dan akurasi arah pasar (Win Rate: LSTM 72,3% vs. GRU 69,8%), yang merupakan temuan\n"
    "            kritis bagi pengembangan strategi pemodelan finansial ke depan.</li>\n"
    "        <li>Memperkaya literatur tentang penerapan metode SHAP sebagai instrumen <em>Explainable AI</em> (XAI)\n"
    "            dalam konteks prediksi harga aset digital yang bersifat sangat volatil.</li>\n"
    "    </ul>\n"
    "    <p><strong>b. Manfaat Praktis (Industri)</strong></p>\n"
    '    <ul class="manfaat">\n'
    "        <li>Menyediakan prototipe sistem <em>Decision Support Dashboard</em> yang dapat langsung diadaptasi\n"
    "            oleh manajer investasi, analis keuangan, dan institusi finansial untuk mendukung pengambilan keputusan\n"
    "            berbasis data (<em>data-driven decision making</em>) di pasar cryptocurrency.</li>\n"
    "        <li>Membantu lembaga keuangan dalam mengukur dan memitigasi risiko paparan aset kripto secara kuantitatif\n"
    "            melalui kalkulasi otomatis metrik risiko seperti <em>Value at Risk</em> (VaR 95%: -2,34%) dan\n"
    "            <em>Sharpe Ratio</em> (LSTM: 1,45) yang dihasilkan dari model terbaik.</li>\n"
    "        <li>Memberikan panduan metodologis yang dapat diimplementasikan oleh praktisi teknologi dalam membangun\n"
    "            sistem prediksi harga kripto yang andal, transparan, dan terintegrasi dengan infrastruktur\n"
    "            <em>Business Intelligence</em> korporasi yang ada.</li>\n"
    "        <li>Berkontribusi pada pengembangan ekosistem keuangan digital yang lebih cerdas dan berbasis kecerdasan\n"
    "            buatan di Indonesia, sejalan dengan agenda transformasi digital nasional.</li>\n"
    "    </ul>\n\n"

    "    <h2>1.6 Batasan Penelitian</h2>\n"
    "    <p>Untuk menjaga fokus dan kedalaman analisis, penelitian ini menetapkan batasan-batasan sebagai berikut:</p>\n"
    '    <ol class="rumusan">\n'
    "        <li><strong>Cakupan Aset:</strong> Penelitian ini secara eksklusif berfokus pada pasangan aset BTC/USDT\n"
    "            (Bitcoin terhadap <em>Tether</em>), dan tidak mencakup aset kripto lain seperti Ethereum (ETH),\n"
    "            Binance Coin (BNB), atau aset digital lainnya.</li>\n"
    "        <li><strong>Sumber Data:</strong> Seluruh data historis diperoleh secara eksklusif dari\n"
    "            <em>Binance Spot API</em> dengan granularitas 1 jam (1h OHLCV), mencakup periode Maret 2021 hingga\n"
    "            proyeksi simulasi 2026, dengan total 43.788 rekaman data.</li>\n"
    "        <li><strong>Model yang Dibandingkan:</strong> Perbandingan model dibatasi pada tiga algoritma: LSTM, GRU\n"
    "            (sebagai model <em>deep learning</em> sekuensial), dan XGBoost (sebagai model <em>ensemble\n"
    "            baseline</em>). Arsitektur lain seperti Transformers, CNN-LSTM, atau model hibrida tidak dicakup\n"
    "            dalam penelitian ini.</li>\n"
    "        <li><strong>Fitur Input:</strong> Model dilatih menggunakan 15 fitur teknikal yang telah ditetapkan\n"
    "            (OHLC, Volume, MA-7, MA-21, RSI-14, MACD, MACD Signal, BB Upper, BB Lower, BB Width, Log Returns,\n"
    "            Rolling Volatility 24h). Faktor eksternal seperti sentimen media sosial, data fundamental\n"
    "            makroekonomi, atau data on-chain tidak diikutsertakan.</li>\n"
    "        <li><strong>Horizon Prediksi:</strong> Evaluasi model difokuskan pada prediksi jangka pendek dalam\n"
    "            jendela validasi 168 jam (satu minggu ke depan) menggunakan metode <em>Walk-Forward Validation</em>.\n"
    "            Prediksi jangka menengah hingga panjang berada di luar cakupan penelitian ini.</li>\n"
    "        <li><strong>Konteks Pengambilan Keputusan:</strong> Prototipe BI Dashboard yang dihasilkan ditujukan\n"
    "            sebagai alat bantu (<em>decision support tool</em>), bukan sebagai sistem perdagangan otomatis\n"
    "            (<em>automated trading system</em>). Keputusan investasi final tetap berada di tangan pengguna\n"
    "            manusia.</li>\n"
    "    </ol>\n\n"

    "    <h2>1.7 Sistematika Penulisan</h2>\n"
    "    <p>Proposal tesis ini disusun secara sistematis dalam struktur bab-bab yang saling berkesinambungan\n"
    "        sebagai berikut:</p>\n"
    '    <div class="sistematika-item">\n'
    "        <strong>BAB I &ndash; PENDAHULUAN</strong> menguraikan konteks dan motivasi penelitian secara menyeluruh,\n"
    "        meliputi Latar Belakang, Identifikasi Masalah, Rumusan Masalah, Tujuan Penelitian, Manfaat Penelitian,\n"
    "        Batasan Penelitian, dan Sistematika Penulisan. Bab ini menetapkan fondasi argumentasi mengapa penelitian\n"
    "        ini relevan, perlu, dan signifikan untuk dilaksanakan.\n"
    "    </div>\n"
    '    <div class="sistematika-item">\n'
    "        <strong>BAB II &ndash; KAJIAN TEORITIS DAN TINJAUAN PUSTAKA</strong> memaparkan landasan teori yang\n"
    "        menopang seluruh metodologi penelitian. Pembahasan mencakup tinjauan kritis terhadap keterbatasan model\n"
    "        prediksi tradisional, evolusi arsitektur Deep Learning berbasis gerbang memori (LSTM dan GRU), konsep\n"
    "        fundamental Big Data dalam konteks finansial, serta kajian literatur terdahulu yang relevan untuk\n"
    "        mengidentifikasi celah penelitian (<em>research gap</em>) yang diisi oleh studi ini.\n"
    "    </div>\n"
    '    <div class="sistematika-item">\n'
    "        <strong>BAB III &ndash; ARSITEKTUR SISTEM DAN METODOLOGI BI FRAMEWORK</strong> menjabarkan secara\n"
    "        rinci rancangan teknis kerangka kerja BI empat lapis yang diusulkan, mencakup: (1) akuisisi dan ingesti\n"
    "        data dari Binance API, (2) pipeline ETL dan normalisasi data, (3) rekayasa fitur teknikal dan komputasi\n"
    "        model prediktif, serta (4) lapisan analitik BI dan presentasi hasil dalam <em>Decision Support\n"
    "        Dashboard</em>.\n"
    "    </div>\n"
    '    <div class="sistematika-item">\n'
    "        <strong>BAB IV &ndash; REKAYASA FITUR DAN OPTIMASI MODEL</strong> memuat pembahasan mendalam tentang\n"
    "        proses rekayasa 15 fitur teknikal yang digunakan, formulasi matematika dari setiap indikator (MACD, RSI,\n"
    "        Bollinger Bands, Rolling Volatility), optimasi hiperparameter menggunakan <em>Grid Search\n"
    "        Cross-Validation</em>, serta evaluasi kontribusi fitur menggunakan nilai SHAP untuk memvalidasi\n"
    "        transparansi model (<em>Explainable AI</em>).\n"
    "    </div>\n"
    '    <div class="sistematika-item">\n'
    "        <strong>BAB V &ndash; HASIL EKSPERIMEN DAN ANALISIS PERBANDINGAN</strong> menyajikan dan menganalisis\n"
    "        hasil empiris dari pengujian Walk-Forward Validation secara komprehensif, memuat tabel komparasi metrik\n"
    "        performa teknis (RMSE, MAE, MAPE), analisis residual, serta transformasi keluaran prediktif ke dalam\n"
    "        metrik risiko bisnis (Win Rate, Sharpe Ratio, Value at Risk). Temuan utama&mdash;termasuk\n"
    "        <em>tradeoff</em> GRU vs. LSTM&mdash;diinterpretasikan secara mendalam dalam konteks investasi nyata.\n"
    "    </div>\n"
    '    <div class="sistematika-item">\n'
    "        <strong>BAB VI &ndash; KESIMPULAN DAN REKOMENDASI</strong> merangkum kontribusi ilmiah dan praktis utama\n"
    "        dari penelitian ini, menjawab secara langsung seluruh rumusan masalah yang telah ditetapkan, serta\n"
    "        mengajukan saran dan arah penelitian lanjutan yang dapat mengembangkan kerangka kerja BI-ML Framework\n"
    "        ini lebih jauh di masa depan.\n"
    "    </div>\n"
    '    <div class="sistematika-item">\n'
    "        <strong>DAFTAR PUSTAKA</strong> memuat seluruh sumber referensi yang digunakan dalam penelitian ini,\n"
    "        disusun sesuai format sitasi IEEE dan bersumber dari jurnal-jurnal terindeks Scopus yang valid dan\n"
    "        dapat diverifikasi.\n"
    "    </div>\n\n"
    "    "
)

new_content = content[:bab1_start] + new_bab1 + content[bab2_start:]

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f'SUCCESS! File updated.')
print(f'Original size: {len(content)} chars')
print(f'New size: {len(new_content)} chars')
print(f'BAB I section size: {len(new_bab1)} chars')
